import React, { Component } from "react";
// import API from "../utils/Api";

import "./style.css";

class Quote extends Component {

    componentDidMount() {
        // const apiURL = ""
    }

    state = {
        price: 0,
        address: [],
        quote: [],
        bookSearch: ""
      };

    
    apiCall = () => {

        // console.log(this.refs.puZip.value);
        // console.log(this.refs.delZip.value);

        var myHeaders = new Headers();
        myHeaders.append("Host", "api.shipengine.com");
        myHeaders.append("API-Key", "TEST_WKICVdlwCQPVDQk5EDv2pZaTX8myOr62GOOeT7jxO1c");
        myHeaders.append("Content-Type", "application/json");
        myHeaders.append('Origin','http://localhost:3000');

        var raw = JSON.stringify({"credential_requirements":
        [
            {"name":"key","title":"RuPMO7nQ4L5s9caJ","type":"string"},
            {"name":"password","title":"The secret password associated with your Authentication Key","type":"string"},
            {"name":"secret","title":"Spot Quote Authentication Key generated by the carrier used for volume pricing only","type":"string"},
            {"name":"securitycode","title":"510088000","type":"string"},
            {"name":"username","title":"100706017","type":"string"}]});

        
        var requestOptions = {
          method: 'POST',
          headers: myHeaders,
          body: raw,
          redirect: 'follow'
        };
        
        fetch("/v-beta/ltl/connections/fxfe", requestOptions)
          .then(response => (response))
          .then(result => console.log(JSON.stringify(result)))
          .catch(error => console.log('error', error));

        //   {"credential_requirements":[{"name":"key","title":"Authentication Key (Production) generated by the carrier","type":"string"},{"name":"password","title":"The secret password associated with your Authentication Key","type":"string"},{"name":"secret","title":"Spot Quote Authentication Key generated by the carrier used for volume pricing only","type":"string"},{"name":"securitycode","title":"Your FedEx account number","type":"string"},{"name":"username","title":"The associated meter number for your FedEx account number.","type":"string"}]}

    // handleFormSubmit = event => {
    //     event.preventDefault();
    //     const collections = [];
    //     // var newAddress ={
    //     //     pickUp: this.refs.puZip.value,
    //     //     deliivery: this.refs.delZip.value
    //     // }
    //     // collections.push(newAddress)
    //     // console.log(newAddress);
    //     // this.setState({address: newAddress})
    //     this.apiCall();

    // }

    // newAddress = () => {
    //     console.log("here")
    // }
    }

    render() {
    return (
        <section className="quoute">
            <div className="container">
            <form>
                <div className="form-group">
                    <label htmlFor="exampleInputEmail1">pu zip code</label>
                    {/* <input ref="puZip" type="text" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="pick up zip"/> */}
                </div>
                <div className="form-group">
                    <label htmlFor="exampleInputPassword1">delivery zip</label>
                    {/* <input ref="delZip" type="text" className="form-control" id="exampleInputPassword1" placeholder="delivery zip"/> */}
                </div>
                <button type="submit" className="btn btn-primary" onClick={this.handleFormSubmit}>submit</button>
                </form>
                <p>{this.state.price}</p>
                </div>
        </section>
    )
    }
}
export default Quote;